name: CI - API Tests (TypeScript/Jest)

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  test:
    name: Node ${{ matrix.node }} on Ubuntu
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [ "20.x" ]  # LTS; matches @types/node 20 in package.json
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Determine working directory
        id: wd
        shell: bash
        run: |
          if [ -f package.json ]; then
            echo "dir=." >> "$GITHUB_OUTPUT"
          elif [ -f task2-backend-api-testing-ts/package.json ]; then
            echo "dir=task2-backend-api-testing-ts" >> "$GITHUB_OUTPUT"
          else
            echo "No package.json found at repo root or in task2-backend-api-testing-ts/"
            ls -la
            exit 1
          fi
          echo "Using workdir: $(cat $GITHUB_OUTPUT)"

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm
          cache-dependency-path: ${{ steps.wd.outputs.dir }}/package-lock.json

      - name: Install dependencies
        working-directory: ${{ steps.wd.outputs.dir }}
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Run tests
        working-directory: ${{ steps.wd.outputs.dir }}
        env:
          CI: true
        run: npm test
